# Generated by Django 5.1.4 on 2026-09-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
